version: '2'

services:

### NGINX Server Container ##################################
    antifraud:
      build: .
      mem_limit: 256m
      #image: antifraud:latest
      ports:
        - '80:5000'
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_DB: 1

    redis:
      image: redis:3.2-alpine
      ports:
        - '6379:6379'
